# Generated by Django 3.1.7 on 2021-03-18 12:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210318_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='79178765665', max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
