# Generated by Django 3.0.5 on 2020-04-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Маленький'), ('MEDIUM', 'Средний'), ('BIG', 'Большой')], default='MEDIUM', max_length=200, verbose_name='Размер'),
        ),
    ]
