# Generated by Django 3.1.7 on 2021-03-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='price_coefficient',
        ),
        migrations.AddField(
            model_name='configuration',
            name='bouquet_price_coefficient',
            field=models.FloatField(default=0, verbose_name='Наценка на цветы в %'),
        ),
    ]
