# Generated by Django 3.1.7 on 2021-03-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210304_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='bouquet_price_coefficient',
            field=models.FloatField(default=1, verbose_name='Наценка на цветы в %'),
        ),
    ]
