# Generated by Django 3.1.7 on 2021-03-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210304_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='size',
            field=models.CharField(choices=[(0, 'Маленький'), (1, 'Средний (как на фото)'), (2, 'Большой')], max_length=7, verbose_name='Размер'),
        ),
    ]
