# Generated by Django 3.1.7 on 2021-03-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210305_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Маленький'), ('MIDDLE', 'Средний (как на фото)'), ('BIG', 'Большой')], max_length=7, verbose_name='Размер'),
        ),
    ]
