# Generated by Django 3.1.7 on 2021-03-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210305_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='big_image',
            field=models.ImageField(blank=True, upload_to='static/uploads/images/', verbose_name='Изображение(большое)'),
        ),
        migrations.AddField(
            model_name='product',
            name='small_image',
            field=models.ImageField(blank=True, upload_to='static/uploads/images/', verbose_name='Изображение(маленькое)'),
        ),
    ]
