# Generated by Django 3.1.7 on 2021-03-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210310_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
