# Generated by Django 3.1.7 on 2021-03-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210313_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Маленький'), ('MIDDLE', 'Средний (как на фото)'), ('BIG', 'Большой')], db_index=True, max_length=7, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bouquets',
            field=models.ManyToManyField(blank=True, db_index=True, to='main.Bouquet', verbose_name='Букеты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(db_index=True, to='main.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Хит'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reasons',
            field=models.ManyToManyField(blank=True, db_index=True, to='main.Reason', verbose_name='Поводы'),
        ),
    ]
