# Generated by Django 3.1.7 on 2021-03-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_cartproduct_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
