# Generated by Django 3.1.7 on 2021-03-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210326_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('PRESENT', 'Подарок'), ('BOUQUET', 'Букет')], max_length=12, verbose_name='Тип'),
        ),
    ]
