# Generated by Django 3.1.7 on 2021-04-01 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210326_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquetflower',
            name='count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
