# Generated by Django 3.1.7 on 2021-03-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_small_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='small_image',
            new_name='image',
        ),
    ]
