# Generated by Django 3.1.7 on 2021-03-22 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210322_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('DELIVERY', 'Доставка'), ('PICKUP', 'Самовызов, скидка 10%')], default='DELIVERY', max_length=8, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='postcard',
            field=models.CharField(choices=[('YES_POSTCARD', 'Приложить'), ('NO_POSTCARD', 'Без открытки')], default='NO_POSTCARD', max_length=12, verbose_name='Открытка'),
        ),
        migrations.AddField(
            model_name='order',
            name='postcard_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст открытки'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.CharField(choices=[('RECIPIENT_IAM', 'Получаю я сам(-а)'), ('RECIPIENT_OTHER', 'Указать получателя')], default='RECIPIENT_IAM', max_length=15, verbose_name='Контакты получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_call',
            field=models.CharField(choices=[('RECIPIENT_CALL_BACK', 'Везти без звонка в указанный промежуток времени'), ('RECIPIENT_NOT_CALL_BACK', 'Позвонить получателю для уточнения адреса')], default='RECIPIENT_CALL_BACK', max_length=23, verbose_name='Адрес получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('CANCEL', 'Отмена'), ('END', 'Завершен')], default='NEW', max_length=6, verbose_name='Статус'),
        ),
    ]
