# Generated by Django 3.1.7 on 2021-03-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210322_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipient_call',
            field=models.CharField(choices=[('RECIPIENT_CALL_BACK', 'Везти без звонка в указанный промежуток времени'), ('RECIPIENT_NOT_CALL_BACK', 'Позвонить получателю для уточнения адреса')], default='RECIPIENT_NOT_CALL_BACK', max_length=23, verbose_name='Адрес получателя'),
        ),
    ]
