# Generated by Django 3.1.7 on 2021-03-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210322_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('DELIVERY', 'Доставка'), ('PICKUP', 'Самовызов, скидка 10%')], default='PICKUP', max_length=8, verbose_name='Способ доставки'),
        ),
    ]
