# Generated by Django 3.1.7 on 2021-03-22 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210322_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='qty',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
