# Generated by Django 3.1.7 on 2021-03-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210322_0625'),
        ('orders', '0007_orderproduct_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='bouquet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bouquet', verbose_name='Букет'),
        ),
    ]
