# Generated by Django 3.1.7 on 2021-03-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210326_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipient_call',
            field=models.CharField(choices=[('NO_CALL_BACK', 'Везти без звонка в указанный промежуток времени'), ('YES_CALL_BACK', 'Позвонить получателю для уточнения адреса')], default='NO_CALL_BACK', max_length=23, verbose_name='Адрес получателя'),
        ),
    ]
