# Generated by Django 3.0.5 on 2020-04-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200411_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Повод',
                'verbose_name_plural': 'Поводы',
            },
        ),
        migrations.AddField(
            model_name='basebouquet',
            name='reason',
            field=models.ManyToManyField(to='app.Reason', verbose_name='Поводы'),
        ),
    ]
