# Generated by Django 3.0.5 on 2020-04-11 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя заказчика')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Номер телефона заказчика')),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя получателя')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона получателя')),
                ('recipient_address', models.CharField(max_length=250, verbose_name='Адрес получателя')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('CANCEL', 'Отмена'), ('END', 'Завершен')], default='NEW', max_length=200, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
