# Generated by Django 3.0.5 on 2020-04-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200411_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='is_add_filter',
            field=models.BooleanField(default=True, verbose_name='Добавить в фильтр'),
        ),
    ]
