# Generated by Django 3.0.5 on 2020-04-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200422_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/bouquets/'),
        ),
    ]
