# Generated by Django 3.0.5 on 2020-04-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_bouquet_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='photo',
        ),
        migrations.AddField(
            model_name='basebouquet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/bouquets/'),
        ),
    ]
