# Generated by Django 3.0.5 on 2020-04-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200423_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebouquet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/bouquets/', verbose_name='Фото'),
        ),
    ]
