# Generated by Django 3.0.5 on 2020-04-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200423_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новика')),
                ('is_hit', models.BooleanField(default=False, verbose_name='Хит')),
                ('discount', models.FloatField(default=0, verbose_name='Скидка')),
                ('size', models.CharField(blank=True, choices=[('SMALL', 'Маленький'), ('MEDIUM', 'Средний'), ('BIG', 'Большой')], max_length=200, null=True, verbose_name='Размер')),
                ('kind', models.CharField(choices=[('PRESENT', 'Подарок'), ('BOUQUET', 'Букет')], default='BOUQUET', max_length=7, verbose_name='Тип продукта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/uploads/bouquets/', verbose_name='Фото')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.BaseBouquet', verbose_name='Базовый букет')),
                ('flowers', models.ManyToManyField(blank=True, through='app.BouquetFlower', to='app.Flower', verbose_name='Цветы')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('title',),
            },
        ),
        migrations.AlterField(
            model_name='bouquetflower',
            name='bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product', verbose_name='Букет'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product', verbose_name='Товар'),
        ),
        migrations.DeleteModel(
            name='Bouquet',
        ),
    ]
