# Generated by Django 3.0.5 on 2020-04-25 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200424_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bouquets', to='app.BaseBouquet', verbose_name='Базовый букет'),
        ),
    ]
