# Generated by Django 3.0.5 on 2020-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200426_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_coefficient', models.FloatField(default=0, verbose_name='Наценка на цветы')),
            ],
        ),
    ]
