# Generated by Django 3.0.5 on 2020-05-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200426_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebouquet',
            name='is_show_on_main_page',
            field=models.BooleanField(default=False, verbose_name='Показать на главной странице'),
        ),
    ]
